In [1]:
import pandas as pd
from pycaret.classification import *

# Load Data

In [2]:
df = pd.read_csv('adult.csv')
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,y
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

# Default Modeling

In [3]:
setup_default = ClassificationExperiment()
setup_default.setup(df, target='y', experiment_name='adult', log_experiment=True)

2023/03/19 18:49:55 INFO mlflow.tracking.fluent: Experiment with name 'adult' does not exist. Creating a new experiment.

In [4]:
best_model_default = setup_default.compare_models()

# Normalize Data

In [5]:
setup_norm = ClassificationExperiment()
setup_norm.setup(df, target='y', experiment_name='adult', log_experiment=True,
                 normalize=True, normalize_method='zscore')

In [6]:
best_model_norm = setup_norm.compare_models()

# Top 5 Predictor

In [9]:
setup_top5 = ClassificationExperiment()
setup_top5.setup(df, target='y', experiment_name='adult', log_experiment=True,
                 feature_selection=True, n_features_to_select=5)

In [10]:
best_model_top5 = setup_top5.compare_models()

In [12]:
setup_top5.dataset_transformed

        age    fnlwgt  education-num  hours-per-week  native-country  y
22242  38.0  183800.0           12.0            40.0        0.246375  0
16194  32.0  108023.0           14.0            40.0        0.246375  0
1667   35.0  107991.0            7.0            45.0        0.246375  0
12334  62.0  144583.0            9.0            40.0        0.246375  0
15890  60.0   82775.0           10.0            55.0        0.246375  0
...     ...       ...            ...             ...             ... ..
16917  36.0  182074.0            9.0            40.0        0.246375  0
32163  36.0  135874.0           13.0            40.0        0.246375  0
21759  23.0  174461.0            9.0            40.0        0.246375  0
2114   25.0   90291.0           13.0            40.0        0.246375  0
18481  44.0  224658.0            9.0            45.0        0.246327  1

[32561 rows x 6 columns]

# Outlier Removal

In [13]:
setup_outr = ClassificationExperiment()
setup_outr.setup(df, target='y', experiment_name='adult', log_experiment=True,
                 remove_outliers=True)

In [14]:
best_model_outr = setup_outr.compare_models()

# Gabungan

In [15]:
setup_all = ClassificationExperiment()
setup_all.setup(df, target='y', experiment_name='adult', log_experiment=True,
                normalize=True, normalize_method='zscore', feature_selection=True,
                n_features_to_select=5, remove_outliers=True)

In [16]:
best_model_all = setup_all.compare_models()